services:
  app:
    image: webdevops/php-nginx:8.4-alpine
    container_name: keevaris-api
    environment:
        - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - traefik-network
      - postgres-network
    working_dir: /app
    ports:
      - 8000:80
      - 8001:8080
    volumes:
      - .:/app
      - .docker/prod.supervisord.conf:/opt/docker/etc/supervisor.d/jobs.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keevaris-api.rule=Host(`test2.keevaris.local`)"
      - "traefik.http.routers.keevaris-api.service=keevaris-api"
      - "traefik.http.services.keevaris-api.loadbalancer.server.port=80"
      - "traefik.http.routers.keevaris-ws.rule=Host(`ws.test2.keevaris.local`)"
      - "traefik.http.routers.keevaris-ws.service=keevaris-ws"
      - "traefik.http.services.keevaris-ws.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-network"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  traefik-network:
    external: true
  postgres-network:
    external: true
