services:
  app:
    image: webdevops/php-nginx:8.4-alpine
    container_name: unit-hq-api
    environment:
        - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - traefik-network
      - postgres-network
    working_dir: /app
    ports:
      - 8000:80
      - 8001:8080
    volumes:
      - .:/app
      - .docker/prod.supervisord.conf:/opt/docker/etc/supervisor.d/jobs.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unit-hq-api.rule=Host(`test2.unithq.local`)"
      - "traefik.http.routers.unit-hq-api.service=unit-hq-api"
      - "traefik.http.services.unit-hq-api.loadbalancer.server.port=80"
      - "traefik.http.routers.unit-hq-ws.rule=Host(`ws.test2.unithq.local`)"
      - "traefik.http.routers.unit-hq-ws.service=unit-hq-ws"
      - "traefik.http.services.unit-hq-ws.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-network"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  traefik-network:
    external: true
  postgres-network:
    external: true
