<?php

declare(strict_types=1);

namespace Tests\Feature\Communications;

use App\Enums\ContactChannelType;
use App\Enums\CredentialStatus;
use App\Events\InboundMessageReceived;
use App\Models\CommsWebhookEvent;
use App\Models\CommunicationAccount;
use App\Models\Contact;
use App\Models\ContactChannel;
use App\Models\Message;
use App\Models\MessageAttachment;
use App\Models\MessageThread;
use App\Models\Site;
use App\Support\Communications\AccountScope;
use App\Support\Communications\Channel;
use App\Support\Communications\Provider;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class InboundTest extends TestCase
{
    use RefreshDatabase;

    private CommunicationAccount $account;

    private string $webhookToken = 'tok-inbound-test';

    protected function setUp(): void
    {
        parent::setUp();

        Site::factory()->create();
        Storage::fake('local');

        $this->account = CommunicationAccount::query()->create([
            'scope' => AccountScope::Company,
            'site_id' => null,
            'channel' => Channel::Email,
            'provider' => Provider::Postmark,
            'is_active' => true,
            'credentials' => ['server_token' => 'test-token'],
            'webhook_url_token' => $this->webhookToken,
            'status' => CredentialStatus::Connected,
        ]);
    }

    public function test_sanitization_and_attachment_caps(): void
    {
        config([
            'communications.inbound.max_attachment_bytes' => 20,
            'communications.inbound.max_total_attachment_bytes' => 100,
        ]);

        $contact = Contact::factory()->create();
        ContactChannel::query()->create([
            'contact_id' => $contact->id,
            'type' => ContactChannelType::Email,
            'value' => 'renter@example.com',
            'is_primary' => true,
            'opted_in' => true,
        ]);

        $payload = $this->inboundFixture('postmark_inbound_multipart.json');
        // ContentLength / decoded size for lease-notes.txt is 29 bytes → over 20 cap
        $payload['Headers'] = [
            ['Name' => 'Message-ID', 'Value' => '<00000000-0000-0000-0000-00000000in01@mtasv.net>'],
        ];

        $this->postJson(
            "/api/webhooks/postmark/{$this->webhookToken}/inbound",
            $payload,
        )->assertOk();

        $message = Message::query()
            ->where('provider_message_id', '00000000-0000-0000-0000-00000000in01')
            ->firstOrFail();

        $html = (string) $message->body_html;
        $this->assertStringNotContainsString('<script', $html);
        $this->assertStringNotContainsString('onload=', $html);
        $this->assertStringNotContainsString('https://evil.example', $html);
        $this->assertStringContainsString('Sounds good', $html);

        $attachment = MessageAttachment::query()->where('message_id', $message->id)->firstOrFail();
        $this->assertTrue($attachment->oversize);
        $this->assertNull($attachment->disk_path);
    }

    public function test_idempotent_and_auto_generated(): void
    {
        Event::fake([InboundMessageReceived::class]);

        $contact = Contact::factory()->create();
        ContactChannel::query()->create([
            'contact_id' => $contact->id,
            'type' => ContactChannelType::Email,
            'value' => 'renter@example.com',
            'is_primary' => true,
            'opted_in' => true,
        ]);

        $payload = $this->inboundFixture('postmark_inbound_multipart.json');
        $payload['Headers'] = [
            ['Name' => 'Message-ID', 'Value' => '<00000000-0000-0000-0000-00000000in01@mtasv.net>'],
            ['Name' => 'Auto-Submitted', 'Value' => 'auto-replied'],
        ];
        $payload['Attachments'] = [];

        $this->postJson(
            "/api/webhooks/postmark/{$this->webhookToken}/inbound",
            $payload,
        )->assertOk();

        $this->postJson(
            "/api/webhooks/postmark/{$this->webhookToken}/inbound",
            $payload,
        )->assertOk();

        $this->assertSame(1, CommsWebhookEvent::query()->count());
        $this->assertSame(1, Message::query()->where('direction', 'inbound')->count());

        $message = Message::query()->where('direction', 'inbound')->firstOrFail();
        $this->assertTrue($message->auto_generated);

        $thread = MessageThread::query()->findOrFail($message->message_thread_id);
        $this->assertSame(0, $thread->unread_count);
        $this->assertNull($thread->last_inbound_at);

        Event::assertDispatched(InboundMessageReceived::class, function (InboundMessageReceived $e) use ($message): bool {
            return $e->messageId === $message->id && $e->autoGenerated === true;
        });
    }

    /**
     * @return array<string, mixed>
     */
    private function inboundFixture(string $name): array
    {
        $path = base_path('tests/fixtures/communications/inbound/'.$name);
        /** @var array<string, mixed> $data */
        $data = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);

        return $data;
    }
}
