<?php

declare(strict_types=1);

namespace App\Listeners;

use App\Events\InboundMessageReceived;
use App\Models\AgentConversation;
use App\Models\AgentConversationMessage;
use App\Models\CommunicationAccount;
use App\Models\Contact;
use App\Models\Message;
use App\Models\MessageThread;
use App\Models\Setting;
use App\Models\Site;
use App\Models\SystemEvent;
use App\Support\Ai\AgentChannelBindings;
use App\Support\Ai\AgentEligibility;
use App\Support\Ai\AgentPrincipal;
use App\Support\Ai\AgentRuntime;
use App\Support\Ai\Enums\AgentAudience;
use App\Support\Ai\Enums\AgentChannel;
use App\Support\Ai\Enums\AgentOrigin;
use App\Support\Ai\Enums\BindingAudience;
use App\Support\Ai\Enums\BindingMode;
use App\Support\Ai\Enums\ConversationState;
use App\Support\Ai\Enums\OutsideHoursPolicy;
use App\Support\Ai\Enums\VerificationLevel;
use App\Support\Ai\Guards\LoopGuard;
use App\Support\Ai\InboundSiteContext;
use App\Support\Ai\ResolvedBinding;
use App\Support\Communications\Channel;
use App\Support\Communications\MessageDirection;
use App\Support\Communications\MessageSource;
use App\Support\Time\SiteClock;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class RespondWithAgent implements ShouldQueue
{
    use InteractsWithQueue;
    use SerializesModels;

    public string $queue = 'ai';

    public function __construct(
        private readonly AgentRuntime $runtime,
        private readonly AgentChannelBindings $bindings,
    ) {}

    public function handle(InboundMessageReceived $event): void
    {
        $message = Message::query()->with(['thread.contact', 'communicationAccount'])->find($event->messageId);
        if ($message === null) {
            return;
        }

        $thread = $message->thread;
        if ($thread === null) {
            return;
        }

        if ($this->shouldIgnore($message, $thread, $event)) {
            return;
        }

        if (AgentConversationMessage::query()->where('subject_message_id', $message->id)->exists()) {
            $this->skip($message, 'duplicate');

            return;
        }

        $agentChannel = $this->agentChannel($event->channel);
        if ($agentChannel === null) {
            $this->skip($message, 'ignored');

            return;
        }

        $account = $message->communicationAccount;
        $siteId = InboundSiteContext::resolve(
            $agentChannel,
            $account instanceof CommunicationAccount ? $account : null,
            $message->to_address,
        );

        $resolved = $this->bindings->resolve($agentChannel, $siteId);
        if ($resolved === null || $resolved->mode === BindingMode::Off) {
            $this->skip($message, 'binding_off');

            return;
        }

        $contact = $thread->contact ?? Contact::query()->find($event->contactId);
        if ($contact === null) {
            $this->skip($message, 'audience');

            return;
        }

        if (! $this->audienceAllows($resolved, $contact, $siteId)) {
            $this->skip($message, 'audience');

            return;
        }

        if (! $this->withinHours($resolved, $siteId)) {
            $this->skip($message, 'outside_hours');

            return;
        }

        if ($this->isHumanOwned($thread)) {
            $this->skip($message, 'human_owned');

            return;
        }

        $definition = $resolved->agent->definition();
        if (! $definition->eligible($contact, $siteId)) {
            $this->skip($message, 'agent_ineligible');

            return;
        }

        if ($this->debounce($message, $thread)) {
            return;
        }

        $conversation = $this->findOrCreateConversation($thread, $resolved, $agentChannel, $contact, $siteId);
        $principal = AgentPrincipal::channelAsserted(
            $contact->id,
            $siteId,
            (string) config('app.locale'),
        );

        $input = (string) ($message->body_text ?? '');

        try {
            $this->runtime->turn(
                $conversation,
                $principal,
                $input,
                subjectMessageId: $message->id,
            );
        } catch (UniqueConstraintViolationException $e) {
            if (AgentConversationMessage::query()->where('subject_message_id', $message->id)->exists()) {
                $this->skip($message, 'duplicate');

                return;
            }

            throw $e;
        }
    }

    private function shouldIgnore(Message $message, MessageThread $thread, InboundMessageReceived $event): bool
    {
        if ($event->autoGenerated || $message->auto_generated || LoopGuard::shouldIgnoreInbound($message)) {
            $this->skip($message, 'ignored');

            return true;
        }

        $channel = $thread->channel instanceof Channel
            ? $thread->channel
            : Channel::tryFrom((string) $thread->channel);
        if ($channel === Channel::Call) {
            $this->skip($message, 'ignored');

            return true;
        }

        return false;
    }

    private function audienceAllows(ResolvedBinding $binding, Contact $contact, ?int $siteId): bool
    {
        return match ($binding->audience) {
            BindingAudience::All, BindingAudience::KnownContacts => true,
            BindingAudience::ExistingTenants => AgentEligibility::hasInForceContractAtSite($contact, $siteId),
        };
    }

    private function withinHours(ResolvedBinding $binding, ?int $siteId): bool
    {
        if ($binding->outsideHours !== OutsideHoursPolicy::Inbox) {
            return true;
        }

        $settings = Setting::general();
        $site = $siteId !== null ? Site::query()->find($siteId) : null;

        return SiteClock::withinWindow($site, $settings->sendWindowStart, $settings->sendWindowEnd);
    }

    private function isHumanOwned(MessageThread $thread): bool
    {
        $conversation = AgentConversation::query()
            ->where('message_thread_id', $thread->id)
            ->where('origin', AgentOrigin::Inbox)
            ->first();
        if ($conversation === null) {
            return false;
        }

        if (in_array($conversation->state, [ConversationState::AwaitingHuman, ConversationState::HandedOff], true)) {
            return true;
        }

        $since = $conversation->agent_handback_at;
        if ($conversation->last_turn_at !== null && ($since === null || $conversation->last_turn_at->gt($since))) {
            $since = $conversation->last_turn_at;
        }
        if ($since === null) {
            return false;
        }

        return Message::query()
            ->where('message_thread_id', $thread->id)
            ->where('direction', MessageDirection::Outbound)
            ->where('source', MessageSource::Manual)
            ->where('created_at', '>', $since)
            ->exists();
    }

    /**
     * @return bool true when the caller should stop
     */
    private function debounce(Message $message, MessageThread $thread): bool
    {
        $newer = Message::query()
            ->where('message_thread_id', $thread->id)
            ->where('direction', MessageDirection::Inbound)
            ->where('id', '>', $message->id)
            ->exists();
        if ($newer) {
            $this->skip($message, 'debounced');

            return true;
        }

        $seconds = (int) config('agents.inbound_debounce_seconds', 20);
        if ($seconds <= 0 || $this->job === null) {
            return false;
        }

        $age = max(0, (int) ($message->created_at?->diffInSeconds(now()) ?? 0));
        if ($age < $seconds) {
            $this->release($seconds - $age);

            return true;
        }

        return false;
    }

    private function findOrCreateConversation(
        MessageThread $thread,
        ResolvedBinding $binding,
        AgentChannel $channel,
        Contact $contact,
        ?int $siteId,
    ): AgentConversation {
        $existing = AgentConversation::query()
            ->where('message_thread_id', $thread->id)
            ->where('origin', AgentOrigin::Inbox)
            ->first();
        if ($existing !== null) {
            return $existing;
        }

        return AgentConversation::query()->create([
            'ai_agent_id' => $binding->agent->id,
            'audience' => AgentAudience::Customer,
            'origin' => AgentOrigin::Inbox,
            'channel' => $channel,
            'contact_id' => $contact->id,
            'site_id' => $siteId,
            'verification_level' => VerificationLevel::ChannelAsserted,
            'state' => ConversationState::Active,
            'locale' => (string) config('app.locale'),
            'message_thread_id' => $thread->id,
        ]);
    }

    private function agentChannel(Channel $channel): ?AgentChannel
    {
        return match ($channel) {
            Channel::Email => AgentChannel::Email,
            Channel::Sms => AgentChannel::Sms,
            Channel::Whatsapp => AgentChannel::Whatsapp,
            default => null,
        };
    }

    private function skip(Message $message, string $reason): void
    {
        SystemEvent::record('ai.inbound.skipped', $message, [
            'reason' => $reason,
            'message_thread_id' => $message->message_thread_id,
        ]);
    }
}
