<?php

declare(strict_types=1);

namespace App\Events;

use App\Support\Communications\Channel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

/**
 * Fact emitted when an inbound message is stored on a contact thread.
 * S11 realtime / lead-chase "replied" exit consume this later — no listeners yet.
 */
class InboundMessageReceived
{
    use Dispatchable;
    use SerializesModels;

    public function __construct(
        public readonly int $messageId,
        public readonly int $messageThreadId,
        public readonly int $contactId,
        public readonly Channel $channel,
        public readonly bool $autoGenerated,
    ) {}
}
