[program:laravel-queue]
command=php /app/artisan queue:work --timeout=3600 --quiet
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=0

[program:laravel-schedule]
command=php /app/artisan queue:work --quiet
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=0

[program:stripe-queue]
command=php /app/artisan queue:work --queue=stripe --timeout=3600 --quiet
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=0
user=application

[program:ai-queue]
command=php /app/artisan queue:work --queue=ai --timeout=180 --tries=1 --backoff=0 --quiet
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=0
user=application

[program:laravel-reverb]
command=php /app/artisan reverb:start --host=0.0.0.0 --port=8080
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=0
user=application
